# Generated by Django 4.0.4 on 2022-05-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('job_discription', models.TextField()),
                ('role', models.CharField(max_length=120)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(null=True)),
                ('qulification', models.CharField(max_length=120, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
